\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{av-statute}[2018/08/11 Alpenverein statutes LaTeX class]

% Extends article-class
\LoadClass[]{article}

% Load some packages
\RequirePackage[utf8]{inputenc} % set utf8 as encoding
\RequirePackage{textcomp} % provides euro and other symbols
\RequirePackagee[sfdefault,lf]{carlito} % use carlito font
\RequirePackage[T1]{fontenc} % set output font to use
\RequirePackage[a4paper]{geometry} % set paper size to a4
\RequirePackage[german]{babel}
\RequirePackage{graphicx}
